platform:ios,'8.0'

target 'GYLib' do

    pod 'YYKit'
    pod 'YTKNetwork'
    pod 'WMPageController'
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'ZFPlayer'
    pod 'JPNavigationController','~> 1.2.7'
    pod 'TZImagePickerController'
    pod 'DZNEmptyDataSet'


end
